collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1136723
  brandStrength: 1
  lightness: 0.5279269
  brandColors:
    - '#FFFDFE'
    - '#021760'
    - '#4380CE'
    - '#ABBCD4'
    - '#947D6D'
  rhythmicContrast: 0.4867792
typography_spectrum: 0.3915145
layout_spectrum: 0.5633727
name: supercoaching
