collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1136722562368959
  brandStrength: 1
  lightness: 0.5377333657816052
  brandColors:
    - '#70756F'
    - '#000201'
    - '#999B8F'
    - '#EAEBE0'
    - '#C2C3B8'
  rhythmicContrast: 0.4867792529985309
typography_spectrum: 0.9702902929857373
layout_spectrum: 0.08741543558426201
name: supercoaching
